### PR TITLE
Adding openSUSE guide for openSUSE users (except Leap)

### PR DESCRIPTION
**Pull request by Runa-Chin**
Hello, I was wondering if I could add some docs for openSUSE Tumbleweed and Slowroll users to the official WayDroid documentation to make it easier for openSUSE users to install WayDroid. Hopefully, my request and addition will be accepted soon. Please accept if there are no errors. Thank you. Feel free to send me suggestions if something wrong.

### CODE REVIEW

**Comment by Runa-Chin** [comment]
@electrikjesus @aleasto Could you please review my request and accept it when it doesn't have something wrong ?

**Comment by aleasto** [comment]
Why `sudo mkdir -p /usr/share/waydroid-extra/images`?

**Comment by Runa-Chin** [comment]
> Why `sudo mkdir -p /usr/share/waydroid-extra/images`?

I guess creating folder before ```waydroid init``` is just suggestions for making folder first before initiation of Waydroid. I know it's optional, but I think the user should know where images folder saved while preparing to download the images.

**Comment by aleasto** [comment]
That's not where Waydroid downloads the android images. That's where distributions can package their own images and Waydroid will skip the download in that case.

**Comment by Runa-Chin** [comment]
> That's not where Waydroid downloads the android images. That's where distributions can package their own images and Waydroid will skip the download in that case.

So,  what should I do now ? Revise it or what ?

**Comment by aleasto** [comment]
Yes, remove it please

**Comment by Runa-Chin** [comment]
> Yes, you can remove it please

image

Done, I revise it.

**Comment by aleasto** [comment]
Thanks. Looks good enough to me.

Any reason you can't use the graphical initializer instead? (just start Waydroid from the applications menu)

**Comment by Runa-Chin** [comment]
> Thanks. Looks good enough to me.
> 
> Any reason you can't use the graphical initializer instead? (just start Waydroid from the applications menu)

Sorry about that. I forgot to add that. But it's okay, whatever the way to init, as long as Waydroid could launch without problem, it's not a big problem about what I'd forgot.

**Pull request merged**
