### PR TITLE
Added a FAQ for Network issue in Waydroid

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
I have created a markdown file to let the users know how to fix the problem of no internet connection in waydroid although the computer is connected to a WiFi network.

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@aleasto @ralphocdol Please review this pull request as a critical issue has been addressed by this pull request.

**Comment by aleasto** [comment]
Already documented

**Comment by SaptarshiSarkar12** [comment]
> Already documented

@aleasto Sorry i could not find it. Can you please provide a link to that specific area where it is documented?

**Comment by aleasto** [comment]
https://docs.waydro.id/debugging/networking-issues

**Pull request closed without merging**
